"""initial schema — full spine data model (CLAUDE.md §15)

Revision ID: 0001
Revises:
Create Date: 2026-06-10

Hand-written rather than autogenerated so the partial unique index (§10) and
the pgvector column are exactly right.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def _json():
    return sa.JSON().with_variant(JSONB(), "postgresql")


def _enum(*values, name):
    return sa.Enum(*values, name=name, native_enum=False)


def upgrade() -> None:
    is_postgres = op.get_bind().dialect.name == "postgresql"
    if is_postgres:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("display_name", sa.String(200), nullable=False),
        sa.Column("email", sa.String(320), nullable=False, unique=True),
    )

    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("owner_id", sa.Uuid(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "branch",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("document_id", sa.Uuid(), sa.ForeignKey("document.id"), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("color", sa.String(32), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_branch_ordinal"),
    )

    op.create_table(
        "node",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("branch_id", sa.Uuid(), sa.ForeignKey("branch.id"), nullable=False),
        sa.Column("type", sa.String(50), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("parameters", _json(), nullable=False),
        sa.Column("declared_inputs", _json(), nullable=False),
    )

    op.create_table(
        "node_execution",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("node_id", sa.Uuid(), sa.ForeignKey("node.id"), nullable=False),
        sa.Column(
            "status",
            _enum("queued", "running", "succeeded", "failed", name="execution_status"),
            nullable=False,
        ),
        sa.Column("label", _enum("draft", "milestone", name="execution_label"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generated_text", sa.Text(), nullable=True),
        sa.Column("input_keys", _json(), nullable=True),
        sa.Column("error", _json(), nullable=True),
        sa.Column("raw_data_uri", sa.String(1000), nullable=True),
        sa.Column(
            "raw_data_state",
            _enum("present", "swept", "unrecoverable", name="raw_data_state"),
            nullable=True,
        ),
        sa.Column("raw_data_meta", _json(), nullable=True),
    )
    # §10: at most one in-flight execution per node — schema-enforced.
    op.create_index(
        "uq_one_inflight_per_node",
        "node_execution",
        ["node_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
        sqlite_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index("ix_execution_node_created", "node_execution", ["node_id", "created_at"])

    if is_postgres:
        from pgvector.sqlalchemy import Vector

        embedding_type = Vector(256)
    else:
        embedding_type = sa.JSON()
    op.create_table(
        "rag_chunk",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "execution_id", sa.Uuid(), sa.ForeignKey("node_execution.id"), nullable=False
        ),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", embedding_type, nullable=False),
    )

    op.create_table(
        "center_node",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "document_id", sa.Uuid(), sa.ForeignKey("document.id"), nullable=False, unique=True
        ),
        sa.Column("markdown", sa.Text(), nullable=False),
    )

    op.create_table(
        "reference_chip",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "center_node_id", sa.Uuid(), sa.ForeignKey("center_node.id"), nullable=False
        ),
        sa.Column("node_id", sa.Uuid(), sa.ForeignKey("node.id"), nullable=False),
        sa.Column(
            "execution_id", sa.Uuid(), sa.ForeignKey("node_execution.id"), nullable=False
        ),
        sa.Column("marker", sa.String(64), nullable=False),
    )

    op.create_table(
        "template",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("owner_id", sa.Uuid(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=True),  # reserved (§8.4)
        sa.Column("name", sa.String(500), nullable=False),
        sa.Column("type", sa.String(50), nullable=False),
        sa.Column("parameters", _json(), nullable=False),
        sa.Column("declared_inputs", _json(), nullable=False),
        sa.Column("color_tag", sa.String(32), nullable=True),
    )

    op.create_table(
        "framework",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("owner_id", sa.Uuid(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=True),  # reserved (§8.4)
        sa.Column("name", sa.String(500), nullable=False),
        sa.Column("structure", _json(), nullable=False),
    )


def downgrade() -> None:
    for table in (
        "framework",
        "template",
        "reference_chip",
        "center_node",
        "rag_chunk",
        "node_execution",
        "node",
        "branch",
        "document",
        "user",
    ):
        op.drop_table(table)
